version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_nosweatcode
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
      #entrypoint: ["sh", "-c", "tail -f /dev/null"]

  certbot:
    image: certbot/certbot
    container_name: certbot_nosweatcode
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

